### ISSUE TITLE
[Bug] Invalid conversion from 'uint8_t' to 'ADS_DEV_IDS_T'

### ISSUE THREAD

**Issue by HarrisonLavins** [sparkfun/SparkFun_Displacement_Sensor_Arduino_Library#1]
### Subject of the issue
When verifying/compiling example sketches in Arduino IDE 1.8.9 the code does not compile with _**error message: invalid conversion from 'uint8_t {aka unsigned char}' to 'ADS_DEV_IDS_T'**_

### Your workbench
* What platform are you using?
MacOS Mojave 10.14.3
* What version of the device are you using? Is there a firmware version?
SparkFun nrf52840 mini 
* How is the device wired to your platform?
N/A
* How is everything being powered?
N/A
* Are there any additional details that may help us help you?
I am using Adafruit nRF52 version 0.10.1 board drivers. See attached photos and text file with verbose compiler output for more info.

[Issue0_Output.docx](https://github.com/sparkfun/SparkFun_Displacement_Sensor_Arduino_Library/files/3317442/Issue0_Output.docx)

<img width="1322" alt="Screen Shot 2019-06-22 at 10 36 05 PM" src="https://user-images.githubusercontent.com/20053754/59970912-7d596680-953f-11e9-96f6-51b44c0f8d3a.png">
<img width="906" alt="Screen Shot 2019-06-22 at 10 37 01 PM" src="https://user-images.githubusercontent.com/20053754/59970913-7d596680-953f-11e9-9e13-f88c5527210c.png">

### Steps to reproduce

Verifying any of the provided example sketches (i.e. Example1_1Axis_BasicReadings, Example2_TestDeviceType) with the Arduino IDE will result in compiler error messages. The issue appears to derive from the SparkFun_Displacement_Sensor_Arduino_Library.cpp file on line 57. _**Simply casting the result from readDeviceType() to type 'ADS_DEV_IDS_T' seemed to make the compiler happy and resolve the issue.**_

### Expected behaviour
Working code, and a happy user.

### Actual behaviour
Compiler errors and a sad user.

**Comment by nseidle** [comment]
Sorry! It seems the Arduino compiler changed it's permissiveness at some point, or else I never had compilable code... Fixed now in v1.2.0.

**Comment by skg91** [comment]
I am getting same error while compiling on arduino DUE. "Arduino\libraries\SparkFun_Angular_Displacement_Sensor_Arduino_Library-1.1.1\src\SparkFun_Displacement_Sensor_Arduino_Library.cpp:57:31: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'ADS_DEV_IDS_T' [-fpermissive]

   axisAmount = readDeviceType(); //Set global sensor axis number
"

Any solution?
